apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: Made-Wro-v2-as
  labels:
    name: Made-Wro-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Made-Wro-v2
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
