apiVersion: apps/v1
kind: Deployment
metadata:
  name: Made-Wro-v2-deployment
  labels:
    app: Made-Wro-v2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Made-Wro-v2
      version: v1
  template:
    metadata:
      labels:
        app: Made-Wro-v2
        version: v1
    spec:
      containers:
      - name: Made-Wro-v2
        image: wro.io/Made-Wro-v2-image
        imagePullPolicy: IfNotPresent
        ports:        
        - containerPort: 12000
        securityContext:
          runAsUser: 1000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v2/actuator/health/liveness
            port: 12000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v2/actuator/health/readiness
            port: 12000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
